Part 1 completed : main screen design
ceddddy/MyPortfolio pull request #1
Opened 2022-10-28 18:24 UTC by ceddddy

# What we did in this phase:

- Added linters and dependencies 

- Added a header and navigation menu
![2022-10-28 20_18_22-](https://user-images.githubusercontent.com/76970719/198705820-418a2de4-3015-4c37-bac5-084cba481c0a.png)

- Added the tittle heading, helper text  
![2022-10-28 20_18_51-](https://user-images.githubusercontent.com/76970719/198706023-dac350b6-221c-43d9-9646-daca00e3b147.png)

- Added social media links
![2022-10-28 20_19_13-](https://user-images.githubusercontent.com/76970719/198706098-1cef8b5d-057c-4217-a5cf-1634b07a7cac.png)

2022-10-28 18:58 UTC, Lizdev-05 requested changes
Hi @ceddddy, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not have a descriptive READme file, kindly use this [template](https://github.com/microverseinc/readme-template/blob/master/README.md) as a guide.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-10-28 20:30 UTC, aimalamiri requested changes
Hi @ceddddy, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![AlmostThereReachGIF](https://user-images.githubusercontent.com/34779928/191347504-9f70659c-a01f-48a1-ad46-b8722d46ffca.gif)

## Highlights

- The header section is designed very well and looks fantastic ✔️ ⭐
- Good job for using the right GitHub Flow 💯
- Awesome file organization 🗃️
- Commits are descriptive and meaningful 👍
- Linters are properly set up and passing 🟢 👍

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-28 20:30 UTC, aimalamiri commented on index.html
> +        <h2 class="navItem">Welcome</h2>
You did a good job 👌but here is how to improve it.
1. Please make sure to put this in the `a` tag, so the user can always navigate to the home page.
2. It's required to follow the exact Figma template, so please make sure to adapt your design with the original one. As you can see the navbar in the original design has no background image, and also please try to update your sizing and spacing as well. These kinds of simple things can significantly improve the design.

![image](https://user-images.githubusercontent.com/34779928/198725757-d281b32e-5b89-441d-aaad-31af7cfe9e22.png)

2022-10-28 20:30 UTC, aimalamiri commented on index.html
> +
You did a great job! 👌but as I mentioned it's very important to follow the Figma design as much as possible, especially the font, sizing, spacing, and colors. So please make sure to update the font type and size in here.

![image](https://user-images.githubusercontent.com/34779928/198726570-153c42f1-f65c-4aae-b1e9-f80fb7d15473.png)

2022-10-29 23:23 UTC, Reem-lab approved these changes
# Hi @Lizdev-05,👋🏻👋🏻

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉🔥🔥💯💯

<img src="https://media3.giphy.com/media/3oz8xAFtqoOUUrsh7W/giphy.gif"/>

## Highlights ✨✨
📌 No Linters error ✅
📌 Descriptive pull request✅
📌 Great working on the set up ✅
📌 Good commit messages ✅
📌 Professional README file ✅

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-30 00:05 UTC, merged